apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
# namespace: hello-gitops
  # newName: hello-gitops
images:
- name: hello-gitops
  newName: 600086062597.dkr.ecr.ap-northeast-2.amazonaws.com/erik-test
  newTag: ed86e46d700b341e856a7942c6273c248b403e20
