apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: myimage
  newTag: asd
  newName: 600086062597.dkr.ecr.ap-northeast-2.amazonaws.com/erik-test
   

  
