apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
# namespace: hello-gitops
  # newName: hello-gitops
images:
- name: /
  newName: /
- name: erik-test
  newName: /
- name: hello-gitops
  newName: /
