name: live-api-action-wf

on:
  push:
    branches: [ master, mystaging ]
  pull_request:
    branches: [ master, mystaging  ]  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:    
    - name: Check out code
      uses: actions/checkout@v2


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and push it to ECR
        echo "ECR_REGISTRY : $ECR_REGISTRY"
        echo "ECR_REPOSITORY : $ECR_REPOSITORY"
        echo "IMAGE_TAG : $IMAGE_TAG"

        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"



  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout kustomize repository
      uses: actions/checkout@v2
      with:
        repository: ericnjin/manifest-k8s-github-actiopn-test
        token: ${{ secrets.MYGITHUB_TOKEN }} # `GH_PAT` is a secret that contains your PAT
        # path: ${{ github.ref }}
        path: manifest-k8s-github-actiopn-test


    - name: Update Kubernetes resources

      
      env:
        IMAGE_TAG: ${{ github.sha }}
        # IMAGE_TAG: $(echo ${{ github.sha }} | cut -c1-8)

      run: |
       echo "IMAGE_TAG : $IMAGE_TAG"
       cd manifest-k8s-github-actiopn-test/${GITHUB_REF##*/}
       cd kustomize/base
       kustomize edit set image myimage=600086062597.dkr.ecr.ap-northeast-2.amazonaws.com/erik-test:$IMAGE_TAG
       cat kustomization.yaml
              
    - name: Commit files
      run: |
        cd manifest-k8s-github-actiopn-test
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git commit -am "Update image tag"
        git push

